### ISSUE TITLE
似乎存在触发 settings.json 变更的副作用

### ISSUE THREAD

**Issue by legends-killer** [phobal/vscode-collapse-node-modules#3]
对于没有配置 settings.json 的项目，使用后会导致 settings.json 被修改：
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/47050572/171542144-54b0566d-5d58-4c35-ad67-2e305cea6e7e.png">

> 像是因为隐藏+展示的逻辑触发了 vs code 的某些机制导致 settings.json 被更新🧐。

**Comment by phobal** [comment]
确实存在这个问题。  
这里收起 `node_modules` 文件夹的原理就是去修改 `.vscode` 下面的 `setting.json` 文件下的 `files.exclude` 字段，将 `**/node_modules` 状态由 `true` 变为 `false`来达到隐藏显示的效果，
这里就会去修改项目下的 `setting.json` 文件，如果之前项目没有 .vscode 这个目录就会创建这个目录，此时 `git` 就会多出这个文件记录。之前有个哥们儿发现了这个问题，还提了一个 [PR](https://github.com/phobal/vscode-collapse-node-modules/pull/1). 他是去修改全局的 `vscode` 配置，确实可以避免这个问题，我在开发模式下用没啥问题，但是我打包发布到应用市场后就存在快捷键不能用的问题，目前还没找到问题发生的原因，所以也就一直没发布新的版本。

解决方法：
可以将 `.vscode` 目录放在 `.gitigore`,  接下来我会处理下这个问题。

**Comment by legends-killer** [comment]
感谢，期待后续解决～

**Comment by magicdawn** [comment]
求 status update
