### ISSUE TITLE
Does not appear to work for subdirectories

### ISSUE THREAD

**Issue by KerryRitter** [phobal/vscode-collapse-node-modules#4]
I am on a project with multiple node_modules folders and it does not appear to work on these subdirectories. File path example: src\MyApp\source\Client\React\node_modules

**Comment by phobal** [comment]
hi, guy, I can't reappear, and try to your example folder, but can't reappear also

https://user-images.githubusercontent.com/9244211/176336714-be9b85e6-8fdb-4920-802b-62f35bf650d8.mp4

if you have trouble, you can give me a example.
